title: Wiki 4D
email: service4D@4d.com
show_downloads: true
description: Vous trouverez sur ce site quelques documents techniques.
baseurl: ""
url: ""
github_username: CGareau
locale:       "fr_FR"

# Build settings
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Other
markdown: kramdown