# Site settings
title: Wiki 4D
email: service4D@4d.com
description:
  en: You will find on this site some technical documents.
  fr: Vous trouverez sur ce site quelques documents techniques.
baseurl: ""
url: ""
github_username: CGareau
index:
  en: home.html
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml

# Build settings
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
markdown: kramdown